### ISSUE TITLE
Grow消息框会被引用winform组件遮挡，无法正常显示

### ISSUE THREAD

**Issue by zhongwcool** [HandyOrg/HandyControl#375]
**Describe the bug**
Grow消息框会被引用winform组件遮挡，无法正常显示，还希望能帮忙看下

**To Reproduce**
复现代码如下:
```C#
 <Grid>
        
        <Border BorderThickness="1" BorderBrush="LightGray" Background="Gray">
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="*" />
                    <RowDefinition Height="20"/>
                </Grid.RowDefinitions>
                <WindowsFormsHost Grid.Row="0">
                    <wf:Panel x:Name="PlayWindow" BackColor="Black" AutoSize="True"/>
                </WindowsFormsHost>
        
                <StatusBar Background="White" Grid.Row="1">
                    <StatusBarItem>
                        <Button Command="{Binding InfoCmd}" Content="通知" Margin="0" Style="{StaticResource ButtonInfo}"/>
                    </StatusBarItem>
                </StatusBar>
            </Grid>
        </Border>
        
        <hc:ScrollViewer VerticalScrollBarVisibility="Hidden" HorizontalAlignment="Right" IsInertiaEnabled="True" IsPenetrating="True">
            <StackPanel hc:Growl.Token="{x:Static data:MessageToken.MainWindow}" VerticalAlignment="Top" Margin="0,10,10,10"/>
        </hc:ScrollViewer>
        
    </Grid>
```

**Additional context**

**Comment by NaBian** [comment]
搜索关键字“wpf空域问题”，希望能帮到你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 上午9:28
收件人:&nbsp;"HandyOrg/HandyControl"<HandyControl@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HandyOrg/HandyControl] Grow消息框会被引用winform组件遮挡，无法正常显示 (#375)





 
Describe the bug
 Grow消息框会被引用winform组件遮挡，无法正常显示，还希望能帮忙看下
 
To Reproduce
 复现代码如下:
  <Grid&gt;                  <Border BorderThickness="1" BorderBrush="LightGray" Background="Gray"&gt;             <Grid&gt;                 <Grid.RowDefinitions&gt;                     <RowDefinition Height="*" /&gt;                     <RowDefinition Height="20"/&gt;                 </Grid.RowDefinitions&gt;                 <WindowsFormsHost Grid.Row="0"&gt;                     <wf:Panel x:Name="PlayWindow" BackColor="Black" AutoSize="True"/&gt;                 </WindowsFormsHost&gt;                          <StatusBar Background="White" Grid.Row="1"&gt;                     <StatusBarItem&gt;                         <Button Command="{Binding InfoCmd}" Content="通知" Margin="0" Style="{StaticResource ButtonInfo}"/&gt;                     </StatusBarItem&gt;                 </StatusBar&gt;             </Grid&gt;         </Border&gt;                  <hc:ScrollViewer VerticalScrollBarVisibility="Hidden" HorizontalAlignment="Right" IsInertiaEnabled="True" IsPenetrating="True"&gt;             <StackPanel hc:Growl.Token="{x:Static data:MessageToken.MainWindow}" VerticalAlignment="Top" Margin="0,10,10,10"/&gt;         </hc:ScrollViewer&gt;              </Grid&gt;
 
Additional context
 Add any other context about the problem here.

**Comment by zhongwcool** [comment]
已解决。感谢。
