### ISSUE TITLE
RelativePanel Below and RightOf Arranges correctly, but LeftOf and Above doestn

### ISSUE THREAD

**Issue by danwalmsley** [HandyOrg/HandyControl#437]
**Describe the bug**

```
<RelativePanel Background="White" VerticalAlignment="Top" HorizontalAlignment="Left">
          <Rectangle Name="rect1" Height="20" Width="20" Fill="Red"   />
          <Rectangle Name="rect2" Height="10" Width="10" Fill="Yellow" RelativePanel.LeftOf="rect1" />
</RelativePanel>
```

Expected:
![image](https://user-images.githubusercontent.com/4672627/87355192-51d46000-c536-11ea-8ca8-a780e3ba229c.png)

Actual:
![image](https://user-images.githubusercontent.com/4672627/87355229-67e22080-c536-11ea-89ed-a20264285211.png)

same happens the the Yellow is above rect1.

Can be worked around but likely an easy fix.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by NaBian** [comment]
![image](https://user-images.githubusercontent.com/17383395/87371129-47a67600-c5b7-11ea-9004-56b7756dbb2a.png)
 we used the same codes and snap a screenshot, the App2 is uwp app, the other is wpf. the correct behaviour is to have no yellow rect, since which is pushed out of the panel.

in the final analysis, there is something wrong in panel size rather than arrange process, tnx for your feedback. we'll deal with this 
issue later, and we need to do more tests.
