### ISSUE TITLE
I want to contribute some features, why I got xaml intelligence error but build success?

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#513]
![image](https://user-images.githubusercontent.com/4510984/99963777-3ffca680-2dcd-11eb-90f2-a1580bd20d52.png)

**Comment by ghost1372** [comment]
These problems are due to Visual Studio ignore it

**Comment by GF-Huang** [comment]
So, how to solve this?

**Comment by ghost1372** [comment]
> So, how to solve this?

I do not know
Maybe older versions of Visual Studio
also These errors may be due to the SharedProject
I recently moved the demo to the Prism, which is out of the Shared mode. You can test it.
https://github.com/ghost1372/HandyControl/tree/PrismDemo

https://github.com/ghost1372/HandyControl/tree/PrismDemo/src/Net_GE45/HandyControlDemo.Prism

**Comment by GF-Huang** [comment]
I'm using `Microsoft Visual Studio Community 2019 16.8.2`.

**Comment by ghost1372** [comment]
> I'm using `Microsoft Visual Studio Community 2019 16.8.2`.

I mean, previous versions of Visual Studio may not have these issues

**Comment by GF-Huang** [comment]
:(

**Comment by ghost1372** [comment]
> :(

Have you tested the new demo?
