### ISSUE TITLE
[Feature request] independent lang packs

### ISSUE THREAD

**Issue by NaBian** [HandyOrg/HandyControl#626]
**Is your feature request related to a problem? Please describe.**
Not all users need internationalization, while hc support it by default, which produce many lang pack folders in output directory.

**Describe the solution you'd like**
We can separate lang packs and download them on demand.

**Comment by ghost1372** [comment]
If this improves development time such as (Add language words in resx, review and Merge PRs) It is a good feature
Otherwise, the following method can restrict language files

`<SatelliteResourceLanguages>en;fa</SatelliteResourceLanguages>`

I think it is a very good suggestion if it is in a way that there is no need to create PR and merge for language pack

**Comment by ghost1372** [comment]
@NaBian can you explain more?
i can see that new nuget version Does not contain language files and for each language there is a nuspec file.
Does anyone who needs a specific language have to create the desired nuget package themselves?

**Comment by NaBian** [comment]
for instance, if you need en lang, just download nuget pack: https://www.nuget.org/packages/HandyControl.Lang.en/
