### ISSUE TITLE
TextBox hc:IsError only works in first time

### ISSUE THREAD

**Issue by zanderzhg** [HandyOrg/HandyControl#691]

**Comment by ghost1372** [comment]
@zanderzhg Please provide more information Code snippet or upload a sample project

**Comment by GF-Huang** [comment]
Same issue. It takes a lot of code to explain this, because it involves data validation. 
I will provide demo to reproduce later.

**Comment by GF-Huang** [comment]
This demo demonstrates the problem, my intention is that the first `TextBox` should not contain the `@` char.

![OT8wTnGxZn](https://user-images.githubusercontent.com/4510984/112759422-7bcaa580-9025-11eb-89d5-9aab4ac1e0ca.gif)

[ValidationDemo.zip](https://github.com/HandyOrg/HandyControl/files/6217624/ValidationDemo.zip)

**Comment by GF-Huang** [comment]
I found that the issue is caused by `TextBox.VerifyData()`.

![image](https://user-images.githubusercontent.com/4510984/112767157-a3cb0080-9047-11eb-9460-43c169b9368f.png)

If I comment this:

![image](https://user-images.githubusercontent.com/4510984/112767176-bcd3b180-9047-11eb-92ff-e5f898e88edd.png)

It works well:

![3B7It91aFQ](https://user-images.githubusercontent.com/4510984/112767198-e1c82480-9047-11eb-9570-d1b12bba5aa5.gif)


---------

**And by the way, how can I set the `VerifyFunc` in `ViewModel`? In other words, is there a `MVVM` way to use `VerifyFunc` for validation?**

How do you think? @NaBian @ghost1372

**Comment by NaBian** [comment]
IsError 已废弃
